sudo: required
services:
        - docker

before_install:
        - docker build -t vikashkumar/multi-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true vikashkumar/multi-test  npm test

after_success:
        - docker build -t vmady/multi-client ./client
        - docker build -t vmady/multi-nginx ./nginx
        - docker build -t vmady/multi-server ./server
        - docker build -t vmady/multi-worker ./worker
        
         # log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
         # Take those images and push them to docker hub
        - docker push vmady/multi-client
        - docker push vmady/multi-nginx
        - docker push vmady/multi-server
        - docker push vmady/multi-worker

deploy:
        provider: elasticbeanstalk
        region: ap-south-1
        app: Multi-docker
        env: MultiDocker-env
        bucket_name:arn: elasticbeanstalk-ap-south-1-007131111482
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id:
                secure: $AWS_ACCESS_KEY
        secret_access_key:
                secure: $AWS_SECRET_KEY

