sudo: required
services:
        - docker

before_install:
        - docker build -t vikashkumar/multi-test -f ./client/Dockerfile.dev ./client

script:
        - docker run -e CI=true vikashkumar/multi-test  npm test

after_success:
        - docker build -t vikashkumar/multi-client ./client
        - docker build -t vikashkumar/multi-nginx ./nginx
        - docker build -t vikashkumar/multi-server ./server
        - docker build -t vikashkumar/multi-worker ./worker
        
          # log in to the docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
          # Take those images and push them to docker hub
        - docker push vikashkumar/multi-client
        - docker push vikashkumar/multi-nginx
        - docker push vikashkumar/multi-server
        - docker push vikashkumar/multi-worker
